name: Deploy (Laravel + Inertia/Vue) to Hostinger

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) PHP/Composer: prod deps
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl, gd, zip
          tools: composer:v2

      - name: Install PHP deps (prod)
        run: composer install --no-interaction --prefer-dist --no-dev --optimize-autoloader

      # 2) Node/Vite build -> public/build
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Node deps & Build
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install --no-audit --no-fund; fi
          npm run build

      # 3) Cleanup (optional)
      - name: Cleanup
        run: rm -rf node_modules tests

      # 4) FTP Deploy (FTPS)
      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: .
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/tests/**
            **/.env
            storage/logs/*.log
          dangerous-clean-slate: false
